eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useAffectedRows=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
mybatis:
  type-aliases-package: com.example.order.dao
  mapper-locations: classpath:mapper/*.xml