eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useAffectedRows=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true