spring:
  application:
    name: zuul

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  retryable: true
  routes:
    ribbon:
      MaxAutoRetries: 2
      MaxAutoRetriesNextServer: 0






