appKey: 1
appSecret: 1
bucket: lynn
endPoint: https://www.aliyun.com
spring:
  profiles:
    active: prod
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: utf-8
    suffix: .html
    template-loader-path: classpath:templates/
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:com.example.demo.mapper/*.xml